<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDUdvIkD\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDUdvIkD/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDUdvIkD.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDUdvIkD\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDUdvIkD\App_KernelProdContainer([
    'container.build_hash' => 'DUdvIkD',
    'container.build_id' => '76a8a54f',
    'container.build_time' => 1707991213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDUdvIkD');
