<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhPXYjx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhPXYjx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRhPXYjx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRhPXYjx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRhPXYjx\App_KernelProdContainer([
    'container.build_hash' => 'RhPXYjx',
    'container.build_id' => '960ce263',
    'container.build_time' => 1707433281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhPXYjx');
