<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOUzWryx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOUzWryx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOUzWryx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOUzWryx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOUzWryx\App_KernelProdContainer([
    'container.build_hash' => 'OUzWryx',
    'container.build_id' => 'deb48593',
    'container.build_time' => 1700433665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOUzWryx');
