<?php

namespace ContainerDUdvIkD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdviceControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdviceController' shared autowired service.
     *
     * @return \App\Controller\AdviceController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdviceController'] = $instance = new \App\Controller\AdviceController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AdviceController', $container));

        return $instance;
    }
}
