<?php

namespace ContainerDUdvIkD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountingRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AccountingRepository' shared autowired service.
     *
     * @return \App\Repository\AccountingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AccountingRepository'] = new \App\Repository\AccountingRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
