<?php

namespace ContainerOUzWryx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderCancelControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OrderCancelController' shared autowired service.
     *
     * @return \App\Controller\OrderCancelController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\OrderCancelController'] = $instance = new \App\Controller\OrderCancelController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\OrderCancelController', $container));

        return $instance;
    }
}
