<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPl4ra83\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPl4ra83/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPl4ra83.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPl4ra83\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPl4ra83\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pl4ra83',
    'container.build_id' => 'f2bce5e3',
    'container.build_time' => 1707991791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPl4ra83');
