<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0edCOG9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0edCOG9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0edCOG9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0edCOG9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0edCOG9\App_KernelDevDebugContainer([
    'container.build_hash' => '0edCOG9',
    'container.build_id' => '0d57267d',
    'container.build_time' => 1697493595,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0edCOG9');
