<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Accounting extends \App\Entity\Accounting implements \Doctrine\Persistence\Proxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carrier' => [parent::class, 'carrier', null],
        "\0".parent::class."\0".'carrierPrice' => [parent::class, 'carrierPrice', null],
        "\0".parent::class."\0".'fullname' => [parent::class, 'fullname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'saleDate' => [parent::class, 'saleDate', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        'carrier' => [parent::class, 'carrier', null],
        'carrierPrice' => [parent::class, 'carrierPrice', null],
        'fullname' => [parent::class, 'fullname', null],
        'id' => [parent::class, 'id', null],
        'product' => [parent::class, 'product', null],
        'quantity' => [parent::class, 'quantity', null],
        'saleDate' => [parent::class, 'saleDate', null],
        'total' => [parent::class, 'total', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
